import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH ?? 'playwright');
const base = process.env.PREVIEW_URL;
assert.ok(base, 'Use run-browser.py to provide a bounded local server');
const channel = process.env.BROWSER_CHANNEL ?? (process.env.CI ? 'chromium' : 'msedge');
const browser = await chromium.launch({ channel, headless: true });
const page = await browser.newPage();
const errors = [];
const external = [];
page.on('pageerror', e => errors.push(e.message));
await page.route('**/*', route => {
  if (route.request().url().startsWith(new URL(base).origin)) return route.continue();
  external.push(route.request().url());
  return route.abort();
});
const id = key => page.locator(`[id="cg-${key}"]`);
const click = name => page.getByRole('button', { name, exact: true }).click();
const output = async () => JSON.parse(await page.locator('#cg-preview-code').textContent());
try {
  await page.goto(base);
  await page.waitForSelector('#config-generator[data-ready="true"]');
  assert.equal(await page.title(), 'Notebook 任务清单生成器');
  assert.equal(await page.getByRole('heading', { name: '任务清单生成器' }).count(), 1);
  assert.equal(await id('seed').inputValue().then(v => v.length), 16);
  const seed = await id('seed').inputValue();
  await id('confirm').check();
  await click('生成随机值');
  assert.notEqual(await id('seed').inputValue(), seed);
  assert.equal(await id('confirm').isChecked(), false, 'Generated field changes apply XML resets too');
  assert.equal((await output()).items[0].enabled, true);
  await id('entries.0.enabled').uncheck();
  assert.equal((await output()).items[0].enabled, false, 'Collection boolean fields must use real checkboxes');
  await id('entries.0.id').fill('kept');
  const token = await id('entries.0.token').inputValue();
  await click('更新标记');
  assert.equal(await id('entries.0.id').inputValue(), 'kept');
  assert.equal(await id('entries.0.enabled').isChecked(), false);
  assert.notEqual(await id('entries.0.token').inputValue(), token);
  assert.equal((await output()).items[0].secret, '••••••••');
  await id('reveal').check();
  assert.equal((await output()).items[0].secret.length, 24);
  await click('添加项目');
  await id('entries.1.id').fill('second');
  const retainedRow = await id('entries.1.id').elementHandle();
  await id('chosen').selectOption('1');
  await click('单项清单');
  assert.equal((await output()).item, 'second');
  await click('移除项目 1');
  assert.equal((await output()).item, 'second');
  assert.equal(await retainedRow.evaluate(node => node.isConnected && node.id === 'cg-entries.0.id'), true,
    'Removing an earlier row retains the same DOM input and updates its error/label path');
  await id('entries.0.id').focus();
  await id('entries.0.id').pressSequentially('-edited');
  assert.equal(await retainedRow.evaluate(node => document.activeElement === node), true);
  await id('entries.0.id').fill('second');
  await click('单个项目');
  assert.equal(await page.getByRole('button', { name: '完整清单', exact: true }).isVisible(), false);
  await id('confirm').check();
  await click('审计信息');
  assert.equal((await output()).confirmed, true);
  await id('project').fill('changed');
  assert.equal(await id('confirm').isChecked(), false);
  assert.equal((await output()).item, 'second', 'Hidden output selection falls back to a visible output');
  await click('全部清单');
  await click('完整清单');
  await id('encoding').selectOption('toml');
  assert.equal(await page.locator('.cg-command').textContent(), 'notebook --input snapshot.toml');
  await id('first').fill('50');
  assert.equal(await page.getByRole('button', { name: '下载配置', exact: true }).isDisabled(), true);
  await id('last').fill('60');
  assert.equal(await page.getByRole('button', { name: '下载配置', exact: true }).isEnabled(), true);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(external, []);
  assert.deepEqual(errors, []);
  console.log('PASS: alternate XML branding, arbitrary fields/collections, generated values, resets, validation and three outputs');

  const failurePage = await browser.newPage();
  failurePage.on('pageerror', e => errors.push(e.message));
  await failurePage.route('**/*', route => route.request().url().startsWith(new URL(base).origin) ? route.continue() : route.abort());
  await failurePage.addInitScript(() => {
    let calls = 0;
    Object.defineProperty(Crypto.prototype, 'getRandomValues', { value(bytes) {
      if (++calls > 1) throw new DOMException('Random unavailable');
      return bytes.fill(0xab);
    } });
  });
  await failurePage.goto(base);
  await failurePage.waitForSelector('#config-generator[data-ready="true"]');
  assert.equal(await failurePage.locator('#cg-seed').inputValue(), '', 'Failed initialization must not apply partial random values');
  assert.match(await failurePage.locator('.cg-status').textContent(), /无法安全生成随机值/);
  await failurePage.getByRole('button', { name: '添加项目', exact: true }).click();
  assert.equal(await failurePage.locator('.cg-user').count(), 1, 'Failed randomness must not add a partial row');
  await failurePage.locator('#cg-project').fill('manual');
  assert.equal(await failurePage.locator('#cg-project').inputValue(), 'manual', 'Manual editing still works');
  assert.deepEqual(errors, []);
  await failurePage.close();
  console.log('PASS: failed Crypto API calls preserve state and allow manual editing');
} finally {
  await browser.close();
}
